# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MailtrapLocal < Formula
  desc "Local email sandbox + catcher: SMTP + Web UI + JSON API in one binary"
  homepage "https://github.com/mailtrap/mailtrap-local"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mailtrap/mailtrap-local/releases/download/v0.2.0/mailtrap-local_0.2.0_darwin_amd64.tar.gz"
      sha256 "ebcc11f51f61bbcb587fd4284be4aa3b0dee71b46c179c25903e16be0db3f107"

      define_method(:install) do
        bin.install "mailtrap-local"
        # Sendmail-replacement symlink — same binary, dispatched on argv[0]
        # basename (see cmd/mailtrap-local/sendmail.go).
        bin.install_symlink "mailtrap-local" => "mailtrap-sendmail"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mailtrap/mailtrap-local/releases/download/v0.2.0/mailtrap-local_0.2.0_darwin_arm64.tar.gz"
      sha256 "08f0885f29b52c0e40283d8df35996df6ce520bbc54eb3ea19149c4c5cae1e6d"

      define_method(:install) do
        bin.install "mailtrap-local"
        # Sendmail-replacement symlink — same binary, dispatched on argv[0]
        # basename (see cmd/mailtrap-local/sendmail.go).
        bin.install_symlink "mailtrap-local" => "mailtrap-sendmail"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mailtrap/mailtrap-local/releases/download/v0.2.0/mailtrap-local_0.2.0_linux_amd64.tar.gz"
      sha256 "e98e24d7ebd00feef145fbb2374a6f17549fd57ba87043371d45918088cbaf99"
      define_method(:install) do
        bin.install "mailtrap-local"
        # Sendmail-replacement symlink — same binary, dispatched on argv[0]
        # basename (see cmd/mailtrap-local/sendmail.go).
        bin.install_symlink "mailtrap-local" => "mailtrap-sendmail"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mailtrap/mailtrap-local/releases/download/v0.2.0/mailtrap-local_0.2.0_linux_arm64.tar.gz"
      sha256 "baff801565aa6b4efdd1ec2b69172888261e0239edf8a0a198652e818407407b"
      define_method(:install) do
        bin.install "mailtrap-local"
        # Sendmail-replacement symlink — same binary, dispatched on argv[0]
        # basename (see cmd/mailtrap-local/sendmail.go).
        bin.install_symlink "mailtrap-local" => "mailtrap-sendmail"
      end
    end
  end

  service do
    run [opt_bin/"mailtrap-local",
         "--http-listen", "127.0.0.1:3550",
         "--smtp-listen", "127.0.0.1:3535",
         "--db", "#{var}/mailtrap-local/db.sqlite3"]
    keep_alive true
    log_path "#{var}/log/mailtrap-local.log"
    error_log_path "#{var}/log/mailtrap-local.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mailtrap-local --version")
  end
end
