# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MailtrapLocal < Formula
  desc "Local email sandbox + catcher: SMTP + Web UI + JSON API in one binary"
  homepage "https://github.com/mailtrap/mailtrap-local"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mailtrap/mailtrap-local/releases/download/v0.4.0/mailtrap-local_0.4.0_darwin_amd64.tar.gz"
      sha256 "ae4558eb5031cee2ca9c44e4ba47491ffaa0c252aa2558f0de5338fb335c26f2"

      define_method(:install) do
        bin.install "mailtrap-local"
        # Sendmail-replacement symlink — same binary, dispatched on argv[0]
        # basename (see cmd/mailtrap-local/sendmail.go).
        bin.install_symlink "mailtrap-local" => "mailtrap-sendmail"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mailtrap/mailtrap-local/releases/download/v0.4.0/mailtrap-local_0.4.0_darwin_arm64.tar.gz"
      sha256 "597769d8ef52ba57da572288df6eb428f19e9b6115b37e45cb8792b03a30f5f3"

      define_method(:install) do
        bin.install "mailtrap-local"
        # Sendmail-replacement symlink — same binary, dispatched on argv[0]
        # basename (see cmd/mailtrap-local/sendmail.go).
        bin.install_symlink "mailtrap-local" => "mailtrap-sendmail"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mailtrap/mailtrap-local/releases/download/v0.4.0/mailtrap-local_0.4.0_linux_amd64.tar.gz"
      sha256 "2d5f5c4b7a33007e2c91eef88e0a4ec8b23576ea0f6ca6630bf0c593b70fc6b5"
      define_method(:install) do
        bin.install "mailtrap-local"
        # Sendmail-replacement symlink — same binary, dispatched on argv[0]
        # basename (see cmd/mailtrap-local/sendmail.go).
        bin.install_symlink "mailtrap-local" => "mailtrap-sendmail"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mailtrap/mailtrap-local/releases/download/v0.4.0/mailtrap-local_0.4.0_linux_arm64.tar.gz"
      sha256 "fcafe40e6aa2f1a401775e62f740505ad9c7509cea0347f3148140ba0441da92"
      define_method(:install) do
        bin.install "mailtrap-local"
        # Sendmail-replacement symlink — same binary, dispatched on argv[0]
        # basename (see cmd/mailtrap-local/sendmail.go).
        bin.install_symlink "mailtrap-local" => "mailtrap-sendmail"
      end
    end
  end

  service do
    run [opt_bin/"mailtrap-local",
         "--http-listen", "127.0.0.1:3550",
         "--smtp-listen", "127.0.0.1:3535",
         "--db", "#{var}/mailtrap-local/db.sqlite3"]
    keep_alive true
    log_path "#{var}/log/mailtrap-local.log"
    error_log_path "#{var}/log/mailtrap-local.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mailtrap-local --version")
  end
end
