# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MailtrapLocal < Formula
  desc "Local email sandbox + catcher: SMTP + Web UI + JSON API in one binary"
  homepage "https://github.com/mailtrap/mailtrap-local"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mailtrap/mailtrap-local/releases/download/v0.1.0/mailtrap-local_0.1.0_darwin_amd64.tar.gz"
      sha256 "b0cd781f1f397958e51589e643fa08325b95bf18ed1cc325fad2fd2e573d5cb4"

      define_method(:install) do
        bin.install "mailtrap-local"
        # Sendmail-replacement symlink — same binary, dispatched on argv[0]
        # basename (see cmd/mailtrap-local/sendmail.go).
        bin.install_symlink "mailtrap-local" => "mailtrap-sendmail"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mailtrap/mailtrap-local/releases/download/v0.1.0/mailtrap-local_0.1.0_darwin_arm64.tar.gz"
      sha256 "4ea6a61838d56808335da933fa54bab6ebbfdda3402fc5ca9d73fdc1d7a29806"

      define_method(:install) do
        bin.install "mailtrap-local"
        # Sendmail-replacement symlink — same binary, dispatched on argv[0]
        # basename (see cmd/mailtrap-local/sendmail.go).
        bin.install_symlink "mailtrap-local" => "mailtrap-sendmail"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mailtrap/mailtrap-local/releases/download/v0.1.0/mailtrap-local_0.1.0_linux_amd64.tar.gz"
      sha256 "7142ff7fb11ff8451508c0fd0f319ba2b957e41e15b4378ae2853f7182342180"
      define_method(:install) do
        bin.install "mailtrap-local"
        # Sendmail-replacement symlink — same binary, dispatched on argv[0]
        # basename (see cmd/mailtrap-local/sendmail.go).
        bin.install_symlink "mailtrap-local" => "mailtrap-sendmail"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mailtrap/mailtrap-local/releases/download/v0.1.0/mailtrap-local_0.1.0_linux_arm64.tar.gz"
      sha256 "1b5c896679ba5ec07741673e3e41acc5a0811e755156a923155af9af738e603b"
      define_method(:install) do
        bin.install "mailtrap-local"
        # Sendmail-replacement symlink — same binary, dispatched on argv[0]
        # basename (see cmd/mailtrap-local/sendmail.go).
        bin.install_symlink "mailtrap-local" => "mailtrap-sendmail"
      end
    end
  end

  service do
    run [opt_bin/"mailtrap-local",
         "--http-listen", "127.0.0.1:3550",
         "--smtp-listen", "127.0.0.1:3535",
         "--db", "#{var}/mailtrap-local/db.sqlite3"]
    keep_alive true
    log_path "#{var}/log/mailtrap-local.log"
    error_log_path "#{var}/log/mailtrap-local.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mailtrap-local --version")
  end
end
